### ISSUE TITLE
Fill the token with the API returns

### ISSUE THREAD

**Issue by Vittor-Emanoel** [shahar-levi/react-token-field#10]
Hello friends!

All good?

About the issue: https://github.com/shahar-levi/react-token-field/issues/8 the problem has not been resolved.

I believe I didn't explain the real problem.

It turns out that the tokens come from an api and so on, but as soon as the component mounts we still don't have the tokens so the return is an empty object.

I'll leave the codesandbox link here and a video.

The idea is that the tokens are filled by the array that returns from the api (think of it as if it were the defaultValue or value property passed to a controlled or uncontrolled component)

**Comment by Vittor-Emanoel** [comment]
![image](https://github.com/shahar-levi/react-token-field/assets/55211291/c4f32dc0-eda6-45b1-88bc-63d4cf48fb12)

I made this change to the code and it worked that way. I believe it is something related.

Successful result: ![Animação](https://github.com/shahar-levi/react-token-field/assets/55211291/82bfa19a-0312-48b8-add7-8251c9f5813c)

**Comment by shahar-levi** [comment]
Thanks,
Merged
