### ISSUE TITLE
Input Token Fails to Monitor tokens Property Values

### ISSUE THREAD

**Issue by Vittor-Emanoel** [shahar-levi/react-token-field#8]
I'm encountering an issue where the input token within my application doesn't seem to be monitoring changes to the tokens property. This behavior persists even after the request to retrieve token values has been resolved. As a result, the token field remains empty, preventing the updated token values from being displayed.

Steps to reproduce:

Initiate a request to fetch token values.
Observe the console log and the input token.
Expected behavior:

The input token should dynamically update with the retrieved token values once the request is resolved.

Actual behavior:

The input token remains empty even after the request is resolved.

Additional context:

The issue appears to be related to the asynchronous nature of the request and the handling of the tokens property within the token field component.

exemple: [codesandbox](https://codesandbox.io/p/devbox/react-tokenfield-yzjck2?file=%2Fsrc%2FApp.tsx%3A24%2C23&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxxpc3xo0006356jqwfw4p80%2522%252C%2522sizes%2522%253A%255B89.08984915520472%252C10.910150844795282%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxxpc3xn0002356j2h1jn2j8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxxpc3xn0004356jl5k01fra%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxxpc3xn0005356jpgpk9vu6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.30348943261715%252C45.69651056738285%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxxpc3xn0002356j2h1jn2j8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxpc3xn0001356jisel0q5v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxxq97sb0002356p747vby2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A24%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A24%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxxpc3xn0002356j2h1jn2j8%2522%252C%2522activeTabId%2522%253A%2522clxxq97sb0002356p747vby2v%2522%257D%252C%2522clxxpc3xn0005356jpgpk9vu6%2522%253A%257B%2522id%2522%253A%2522clxxpc3xn0005356jpgpk9vu6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clxxpdro10008356jfiz2oqsm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxxpdro10008356jfiz2oqsm%2522%257D%252C%2522clxxpc3xn0004356jl5k01fra%2522%253A%257B%2522id%2522%253A%2522clxxpc3xn0004356jl5k01fra%2522%252C%2522activeTabId%2522%253A%2522clxxpc3xn0003356j1tnn9tsx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxxpc3xn0003356j1tnn9tsx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clxxpc49v0012dif82kd2fem1%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clxxpceu3006q356jma6pshl1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Console: 
![image](https://github.com/shahar-levi/react-tokenfield/assets/55211291/391a9b27-f96f-4ce0-874f-d64620ee341c)

**Comment by shahar-levi** [comment]
Fixed

**Comment by shahar-levi** [comment]
Fixed !!react-token-field@2.0.10
