### ISSUE TITLE
Styling Tokens with Tailwind CSS

### ISSUE THREAD

**Issue by Vittor-Emanoel** [shahar-levi/react-token-field#9]
Hello again!

Is it possible to style tokens using Tailwind CSS?

and not just through the getTokenCss function?

it would be something more or less like this:

`<TokenField
        tokens={emails}
        onChange={({ tokens }) => console.log(tokens)}
        className="resize-none py-1 -px-2"
  />`

**Comment by shahar-levi** [comment]
Fix v2.0.10 
BTW, the package name changed to react-token-field.
